# Local development dependencies including docs building, website upload, ASV benchmark
name: POP-TOOLS
channels:
  - conda-forge
dependencies:
  - bitarray>=2.9.0
  - numpy>=1.26.2
  - packaging>=23.2
  - pandas>=2.1.4
  - polars-lts-cpu==1.8.2  # Note the quotes for exact version specifications
  - pytz>=2023.3
  - scipy>=1.11.4
  - six>=1.16.0
  - tzdata>=2023.3
  - typing-extensions  # 'typing' is typically included in Python; use 'typing-extensions' if needed